[package]
name = "fs-sync"
version = "0.1.0"
authors = ["David Barsky <me@davidbarsky.com>"]

[dependencies]
notify = "4.0.0"
loggerv = "0.4"
log = "0.3"
structopt = "0.1.0"
structopt-derive = "0.1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
ssh2 = "0.3"
ignore = "0.3"

[features]
default = []